version: '3.8'
services:
  web:
    container_name: backend_web
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      
  db:
    container_name: backend_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unilink
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: backend_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  mysql-data:
